version: 0.0
"Resources": [
  {
    "TargetService": {
      "Type": "AWS::ECS::Service",
          "Properties": {
              "TaskDefinition": "arn:aws:ecs:us-east-1:979459205431:task-definition/python:latest",
              "LoadBalancerInfo": {
                  "ContainerName": "myapp_python",
                  "ContainerPort": 5000
              }
          }             
      }
  }
]
