version: 0.0
"Resources": [
  {
    "TargetService": {
      "Type": "AWS::ECS::Service",
          "Properties": {
              "TaskDefinition": "arn:aws:ecs:us-east-1:175939439604:task-definition/python:latest",
              "LoadBalancerInfo": {
                  "ContainerName": "myapp",
                  "ContainerPort": 5000
              }
          }             
      }
  }
]
"Hooks": [
    {
      "BeforeInstall": "BeforeInstallHookLambdaFunctionName"
    },
    {
      "AfterInstall": "AfterInstallHookLambdaFunctionName"
    },
    {
      "AfterAllowTestTraffic": "AfterAllowTestTrafficHookLambdaFunctionName"
    },
    {
      "BeforeAllowTraffic": "SanityTestHookLambdaFunctionName"
    },
    {
      "AfterAllowTraffic": "ValidationTestHookLambdaFunctionName"
    }
  ]
}
