version: 0.2

phases:
  install:
    commands:
#       - echo "in install phase for docker"
#       - sudo ./aws.sh
      - sudo yum install docker -y
#       - sudo service docker start
#       - systemctl start docker
      
      
  pre_build:
    commands:
      - echo "in pre build phase"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979459205431.dkr.ecr.us-east-1.amazonaws.com
      - docker tag mydocker-test:latest 979459205431.dkr.ecr.us-east-1.amazonaws.com/mydocker-test:latest
      - docker push 979459205431.dkr.ecr.us-east-1.amazonaws.com/mydocker-test:latest
    on-failure: ABORT   

artifacts:
  files:
    - '**/*'
