version: '3'
volumes:
  db:

services:
  db:
    image: mysql
    restart: always
    volumes:
       - db:/var/lib/mysql
    environment:
        #database: example
        # host=: db
        # user: root
        MYSQL_USER: root
        MYSQL_DATABASE: mysql
        MYSQL_ROOT_PASSWORD: password
    # ports:
    #   - 3306:3306

    command: --default-authentication-plugin=mysql_native_password

  app:
    build : .
    depends_on :
      - db
    environment:
        DB_HOST: db
        DB_USER: root
        DB_PASSWORD: password
        DB_NAME: mysql

    ports:
      - 5000:5000
    
